<template>
    <Son :list="list.arr"></Son>
</template>

<script lang="ts" setup>
    // @ts-ignore
    import Son from "./Son.vue"
    import { reactive } from "vue"
    let list = reactive({
        arr: [
            { height: 300, background:'red' },
            { height: 500, background:'yellow' },
            { height: 200, background:'blue' },
            { height: 800, background:'green' },
            { height: 100, background:'yellow' },
            { height: 500, background:'green' },
            { height: 600, background:'red' },
            { height: 700, background:'red' },
            { height: 900, background:'yellow' },
            { height: 200, background:'red' },
            { height: 300, background:'gray' },
            { height: 700, background:'gray' },
            { height: 300, background:'red' },
            { height: 500, background:'yellow' },
            { height: 200, background:'blue' },
            { height: 800, background:'green' },
            { height: 100, background:'yellow' },
            { height: 500, background:'green' },
            { height: 600, background:'red' },
            { height: 700, background:'red' },
            { height: 900, background:'yellow' },
            { height: 200, background:'red' },
            { height: 300, background:'gray' },
            { height: 700, background:'gray' },
            { height: 300, background:'red' },
            { height: 500, background:'yellow' },
            { height: 200, background:'blue' },
            { height: 800, background:'green' },
            { height: 100, background:'yellow' },
            { height: 500, background:'green' },
            { height: 600, background:'red' },
            { height: 700, background:'red' },
            { height: 900, background:'yellow' },
            { height: 200, background:'red' },
            { height: 300, background:'gray' },
            { height: 700, background:'gray' },
            { height: 300, background:'red' },
            { height: 500, background:'yellow' },
            { height: 200, background:'blue' },
            { height: 800, background:'green' },
            { height: 100, background:'yellow' },
            { height: 500, background:'green' },
            { height: 600, background:'red' },
            { height: 700, background:'red' },
            { height: 900, background:'yellow' },
            { height: 200, background:'red' },
            { height: 300, background:'gray' },
            { height: 700, background:'gray' },
            { height: 300, background:'red' },
            { height: 500, background:'yellow' },
            { height: 200, background:'blue' },
            { height: 800, background:'green' },
            { height: 100, background:'yellow' },
            { height: 500, background:'green' },
            { height: 600, background:'red' },
            { height: 700, background:'red' },
            { height: 900, background:'yellow' },
            { height: 200, background:'red' },
            { height: 300, background:'gray' },
            { height: 700, background:'gray' },
            { height: 300, background:'red' },
            { height: 500, background:'yellow' },
            { height: 200, background:'blue' },
            { height: 800, background:'green' },
            { height: 100, background:'yellow' },
            { height: 500, background:'green' },
            { height: 600, background:'red' },
            { height: 700, background:'red' },
            { height: 900, background:'yellow' },
            { height: 200, background:'red' },
            { height: 300, background:'gray' },
            { height: 700, background:'gray' },
            { height: 300, background:'red' },
            { height: 500, background:'yellow' },
            { height: 200, background:'blue' },
            { height: 800, background:'green' },
            { height: 100, background:'yellow' },
            { height: 500, background:'green' },
            { height: 600, background:'red' },
            { height: 700, background:'red' },
            { height: 900, background:'yellow' },
            { height: 200, background:'red' },
            { height: 300, background:'gray' },
            { height: 700, background:'gray' },
        ]
    })
</script>

<style scoped>

</style>
